# Generated by Django 5.0.6 on 2024-05-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('Madhypradesh', 'Madhypradesh'), ('Bhihar', 'Bhihar')], max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('loaction', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='image')),
                ('docs', models.FileField(blank=True, upload_to='docs')),
            ],
        ),
    ]
